HW 18. Playwright actions, assertions
viaylya1/aqa-playwright pull request #2
Opened 2024-04-01 08:37 UTC by viaylya1

2024-04-01 09:01 UTC, sttaran requested changes

2024-04-01 09:01 UTC, sttaran commented on tests/pw_actions_assertions/registration_form.spec.js
> +    await signInBtn.click();
we have sign up button on welcome page

2024-04-01 09:01 UTC, sttaran commented on tests/pw_actions_assertions/registration_form.spec.js
> +        await expect(registerBtn).toBeDisabled();
add check for input border color if invalid value is entered

2024-04-01 09:01 UTC, sttaran commented on tests/pw_actions_assertions/registration_form.spec.js
> +        await nameField.clear();
use loop when you have multiple variants, it is really good moment to use DDT

2024-04-01 09:13 UTC, viaylya1 commented on tests/pw_actions_assertions/registration_form.spec.js
> +        await expect(registerBtn).toBeDisabled();
I check it at the end of negative test for each field. 
![image](https://github.com/viaylya1/aqa-playwright/assets/29942994/1840cdf2-5407-4a1c-8533-267c04749f6b)

Should I check it after each negative test.step?

2024-04-02 19:42 UTC, viaylya1 commented on tests/pw_actions_assertions/registration_form.spec.js
> +    await signInBtn.click();
Fixed

2024-04-02 19:42 UTC, viaylya1 commented on tests/pw_actions_assertions/registration_form.spec.js
> +        await expect(registerBtn).toBeDisabled();
I checked, border is checked in all fields

2024-04-02 19:43 UTC, viaylya1 commented on tests/pw_actions_assertions/registration_form.spec.js
> +        await nameField.clear();
All tests are re-written with using "for of" loop.

2024-04-03 07:03 UTC, sttaran approved these changes

2024-04-03 07:39 UTC, merged